@extends('layouts.app')

@section('title', 'Create a ticket')
@section('topline', 'Tell us what’s going on')

@section('content')
    <div class="mx-auto max-w-3xl">
        <a href="{{ route('tickets.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600"><span aria-hidden="true">←</span> Back to my tickets</a>
        <section class="mt-5 ui-card overflow-hidden">
            <div class="border-b border-slate-100 bg-gradient-to-r from-indigo-50 to-white px-6 py-7 sm:px-8"><p class="text-sm font-semibold text-indigo-700">New support request</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">What do you need help with?</h1><p class="mt-2 max-w-xl text-sm leading-6 text-slate-500">Share a few details so our IT team can get started. You can follow the conversation from your ticket.</p></div>
            <form method="POST" action="{{ route('tickets.store') }}" enctype="multipart/form-data" class="space-y-6 px-6 py-7 sm:px-8" data-ticket-form data-loading-form>
                @csrf
                <input type="hidden" name="_html_form" value="1">
                <div><label for="title" class="mb-1.5 block text-sm font-semibold text-slate-800">Title <span class="text-rose-600">*</span></label><input id="title" name="title" type="text" required maxlength="255" value="{{ old('title') }}" placeholder="A short summary of the issue" class="w-full rounded-lg border-slate-300 shadow-sm placeholder:text-slate-400 focus:border-indigo-500 focus:ring-indigo-500 @error('title') border-rose-400 @enderror" aria-describedby="title-help title-error"><p id="title-help" class="mt-1.5 text-xs text-slate-500">Keep it clear and specific.</p>@error('title')<p id="title-error" class="mt-1 text-sm font-medium text-rose-700">{{ $message }}</p>@enderror</div>
                <div><label for="description" class="mb-1.5 block text-sm font-semibold text-slate-800">Description <span class="text-rose-600">*</span></label><textarea id="description" name="description" rows="7" required maxlength="20000" placeholder="What happened? What were you trying to do? Include any error message that might help." class="w-full rounded-lg border-slate-300 shadow-sm placeholder:text-slate-400 focus:border-indigo-500 focus:ring-indigo-500 @error('description') border-rose-400 @enderror" aria-describedby="description-error">{{ old('description') }}</textarea>@error('description')<p id="description-error" class="mt-1 text-sm font-medium text-rose-700">{{ $message }}</p>@enderror</div>
                <div class="grid gap-5 sm:grid-cols-2">
                    <div><label for="category_id" class="mb-1.5 block text-sm font-semibold text-slate-800">Category <span class="text-rose-600">*</span></label><select id="category_id" name="category_id" required class="w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 @error('category_id') border-rose-400 @enderror"><option value="">Choose a category</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<p class="mt-1 text-sm font-medium text-rose-700">{{ $message }}</p>@enderror</div>
                    <div><label for="priority_id" class="mb-1.5 block text-sm font-semibold text-slate-800">Priority <span class="text-rose-600">*</span></label><select id="priority_id" name="priority_id" required class="w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 @error('priority_id') border-rose-400 @enderror"><option value="">Choose a priority</option>@foreach ($priorities as $priority)<option value="{{ $priority->id }}" @selected((string) old('priority_id') === (string) $priority->id)>{{ $priority->name }}</option>@endforeach</select>@error('priority_id')<p class="mt-1 text-sm font-medium text-rose-700">{{ $message }}</p>@enderror</div>
                </div>
                <div data-file-picker><label for="file" class="mb-1.5 block text-sm font-semibold text-slate-800">Attachment <span class="font-normal text-slate-500">(optional)</span></label><input id="file" name="file" type="file" accept=".pdf,.txt,.png,.jpg,.jpeg,.doc,.docx,.xls,.xlsx" class="block w-full cursor-pointer rounded-lg border border-slate-300 text-sm text-slate-600 file:mr-4 file:border-0 file:bg-slate-100 file:px-4 file:py-2.5 file:text-sm file:font-semibold file:text-slate-700 hover:file:bg-slate-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600"><p class="mt-1.5 text-xs text-slate-500">Attach a screenshot or document (up to 10 MB).</p>@error('file')<p class="mt-1 text-sm font-medium text-rose-700">{{ $message }}</p>@enderror<div data-file-details class="mt-3 hidden items-center justify-between gap-3 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5"><span data-file-name class="min-w-0 truncate text-sm font-medium text-slate-700"></span><span data-file-size class="shrink-0 text-xs text-slate-500"></span><button type="button" data-file-remove class="shrink-0 rounded-md px-2 py-1 text-xs font-semibold text-rose-700 hover:bg-rose-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-rose-600">Remove</button></div></div>
                <div class="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><a href="{{ route('tickets.index') }}" class="rounded-lg border border-slate-300 px-5 py-3 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600">Cancel</a><button type="submit" data-loading-label="Submitting…" class="rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Submit ticket <span aria-hidden="true">→</span></button></div>
            </form>
        </section>
    </div>
@endsection
