@extends('layouts.app')

@section('title', 'My tickets')
@section('topline', 'Your requests')

@section('content')
    @php($hasFilters = collect(['search', 'status', 'priority_id', 'category_id'])->contains(fn ($key) => request()->filled($key)))
    <section class="ui-page-toolbar mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><p class="ui-eyebrow">Support requests</p><h1 class="ui-page-title text-3xl">My tickets</h1><p class="mt-2 text-sm text-slate-500">Follow progress and find any request you’ve sent to IT.</p></div>
        <a href="{{ route('tickets.create') }}" class="inline-flex items-center justify-center gap-2 ui-button-primary px-5 py-3">＋ Create ticket</a>
    </section>

    <section class="ticket-filter-card mb-5 overflow-hidden rounded-xl border border-gray-100 bg-white shadow-md" aria-label="Search and filter tickets">
        <div class="mb-4 flex items-center gap-3 border-b border-gray-100 bg-indigo-50/50 px-4 pb-3 pt-3.5 sm:px-5"><span class="grid size-9 place-items-center rounded-xl bg-indigo-100 text-indigo-600" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M4 5h16l-6.5 7.5v5l-3 1.5v-6.5L4 5Z" /></svg></span><div><h2 class="text-sm font-bold text-slate-900">Find a ticket</h2><p class="mt-0.5 text-xs text-slate-500">Search your requests or narrow them by status</p></div></div>
        <form method="GET" action="{{ route('tickets.index') }}" class="grid grid-cols-1 gap-4 px-4 pb-4 sm:grid-cols-2 sm:px-5 sm:pb-5 xl:grid-cols-4">
            <label class="sm:col-span-2 xl:col-span-4"><span class="mb-1.5 block text-[11px] font-bold uppercase tracking-wider text-gray-500">Search tickets</span><input type="search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Ticket number or title" class="w-full rounded-lg border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-700 shadow-sm transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 focus:outline-none"></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Status</span><select name="status" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status->slug }}" @selected(($filters['status'] ?? '') === $status->slug)>{{ $status->name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Priority</span><select name="priority_id" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="">All priorities</option>@foreach ($priorities as $priority)<option value="{{ $priority->id }}" @selected((string) ($filters['priority_id'] ?? '') === (string) $priority->id)>{{ $priority->name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Category</span><select name="category_id" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="">All categories</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) ($filters['category_id'] ?? '') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Sort by</span><select name="sort" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="newest" @selected(($filters['sort'] ?? 'newest') === 'newest')>Newest first</option><option value="oldest" @selected(($filters['sort'] ?? '') === 'oldest')>Oldest first</option><option value="updated" @selected(($filters['sort'] ?? '') === 'updated')>Recently updated</option></select></label>
            <div class="flex items-center justify-end gap-2 border-t border-sky-100 pt-4 sm:col-span-2 xl:col-span-4"><span class="mr-auto rounded-full bg-sky-100 px-3 py-1 text-xs font-semibold text-sky-800">{{ $tickets->total() }} {{ Str::plural('ticket', $tickets->total()) }}</span><a href="{{ route('tickets.index') }}" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600 transition hover:bg-sky-50 hover:text-sky-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600">Clear</a><button type="submit" class="ticket-filter-submit rounded-lg px-4 py-2.5 text-sm font-semibold shadow-sm transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600">Apply filters</button></div>
        </form>
    </section>

    <section class="ui-card overflow-hidden">
        @if ($tickets->isEmpty())
            <div class="px-6 py-16 text-center"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-slate-100 text-xl text-slate-600" aria-hidden="true">⌕</span><h2 class="mt-4 text-lg font-bold text-slate-900">{{ $hasFilters ? 'No matching tickets' : 'Nothing here yet' }}</h2><p class="mt-1 text-sm text-slate-500">{{ $hasFilters ? 'Try changing or clearing your filters.' : 'Create a ticket and your requests will be listed here.' }}</p>@if ($hasFilters)<a href="{{ route('tickets.index') }}" class="mt-5 inline-flex ui-button-secondary">Clear filters</a>@else<a href="{{ route('tickets.create') }}" class="mt-5 inline-flex ui-button-primary">Create a ticket</a>@endif</div>
        @else
            <div class="hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><thead class="ui-table-head"><tr><th class="px-6 py-3 font-semibold">Ticket</th><th class="px-4 py-3 font-semibold">Category</th><th class="px-4 py-3 font-semibold">Priority</th><th class="px-4 py-3 font-semibold">Status</th><th class="px-4 py-3 font-semibold">Created</th><th class="px-4 py-3 font-semibold">Updated</th><th class="px-6 py-3"><span class="sr-only">Action</span></th></tr></thead><tbody class="divide-y divide-slate-100">
                @foreach ($tickets as $ticket)
                    <tr class="hover:bg-slate-50/80"><td class="px-6 py-4"><a href="{{ route('tickets.show', $ticket) }}" class="font-semibold text-slate-900 hover:text-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600">{{ $ticket->title }}</a><p class="mt-1 text-xs font-medium text-slate-500">{{ $ticket->ticket_number }}</p></td><td class="px-4 py-4 text-slate-600">{{ $ticket->category->name }}</td><td class="px-4 py-4"><x-ticket-priority-badge :priority="$ticket->priority" /></td><td class="px-4 py-4"><x-ticket-status-badge :status="$ticket->status" /></td><td class="whitespace-nowrap px-4 py-4 text-slate-500">{{ $ticket->created_at->format('M j, Y') }}</td><td class="whitespace-nowrap px-4 py-4 text-slate-500">{{ $ticket->updated_at->format('M j, Y') }}</td><td class="px-6 py-4 text-right"><a href="{{ route('tickets.show', $ticket) }}" class="font-semibold text-indigo-700 hover:text-indigo-900">View <span aria-hidden="true">→</span></a></td></tr>
                @endforeach
            </tbody></table></div>
            <ul class="divide-y divide-slate-100 md:hidden">
                @foreach ($tickets as $ticket)
                    <li class="p-4"><a href="{{ route('tickets.show', $ticket) }}" class="block rounded-xl focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600"><span class="flex items-start justify-between gap-3"><span class="font-semibold text-slate-900">{{ $ticket->title }}</span><x-ticket-status-badge :status="$ticket->status" /></span><span class="mt-1 block text-xs font-medium text-slate-500">{{ $ticket->ticket_number }} · {{ $ticket->category->name }}</span><span class="mt-3 flex items-center justify-between"><x-ticket-priority-badge :priority="$ticket->priority" /><span class="text-xs text-slate-500">Updated {{ $ticket->updated_at->format('M j, Y') }}</span></span></a></li>
                @endforeach
            </ul>
            <div class="border-t border-slate-100 px-4 py-4 sm:px-6">{{ $tickets->links() }}</div>
        @endif
    </section>
@endsection
