<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" aria-labelledby="assigned-ticket-list-heading">
    <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 bg-gradient-to-r from-indigo-50/70 via-white to-violet-50/40 px-5 py-4 sm:px-6">
        <div><h2 id="assigned-ticket-list-heading" class="text-base font-bold text-slate-950">{{ $heading }}</h2><p class="mt-1 text-xs text-slate-500">{{ $description }}</p></div>
        <span class="rounded-full border border-indigo-100 bg-white px-3 py-1 text-xs font-bold text-indigo-800 shadow-sm">{{ $tickets->total() }} {{ Str::plural('ticket', $tickets->total()) }}</span>
    </div>

    @if ($showFilter)
        <form method="GET" action="{{ route('technician.tickets.index') }}" class="grid gap-3 border-b border-slate-100 bg-slate-50/70 p-4 sm:grid-cols-[minmax(0,1fr)_15rem_auto] sm:items-end sm:px-6">
            @if ($statusFilter !== 'all')<input type="hidden" name="status" value="{{ $statusFilter }}">@endif
            <label><span class="mb-1.5 block text-[11px] font-bold uppercase tracking-wider text-slate-500">Search</span><input name="search" type="search" value="{{ $filters['search'] ?? '' }}" maxlength="150" placeholder="Ticket, subject, employee" class="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm shadow-sm transition placeholder:text-slate-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"></label>
            <label><span class="mb-1.5 block text-[11px] font-bold uppercase tracking-wider text-slate-500">Queue</span><select name="status" class="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm shadow-sm transition focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"><option value="all" @selected($statusFilter === 'all')>All assigned tickets</option>@foreach (\App\Enums\TicketStatusSlug::cases() as $status)<option value="{{ $status->value }}" @selected($statusFilter === $status->value)>{{ $status->label() }}</option>@endforeach<option value="sent_back" @selected($statusFilter === 'sent_back')>Sent back / needs work</option><option value="completed" @selected($statusFilter === 'completed')>Completed / closed</option></select></label>
            <div class="flex justify-end gap-2"><a href="{{ route('technician.tickets.index') }}" class="inline-flex min-h-10 items-center rounded-xl px-3 text-sm font-semibold text-slate-600 transition hover:bg-white hover:text-rose-700">Clear</a><button type="submit" class="ui-button-primary min-h-10 px-4">Apply filters</button></div>
        </form>
    @else
        <div class="flex flex-wrap gap-2 border-b border-slate-100 px-5 py-3 sm:px-6">
            @foreach ($stats as $stat)
                <a href="{{ route('technician.tickets.index', ['status' => $stat['status']]) }}" class="rounded-full border px-3 py-1.5 text-xs font-semibold transition {{ $statusFilter === $stat['status'] ? 'border-indigo-200 bg-indigo-50 text-indigo-800' : 'border-slate-200 bg-white text-slate-600 hover:border-indigo-200 hover:bg-indigo-50/60 hover:text-indigo-800' }}">{{ $stat['label'] }} <span class="ml-1 tabular-nums opacity-75">{{ $stat['count'] }}</span></a>
            @endforeach
        </div>
    @endif

    @if ($tickets->isEmpty())
        <div class="px-6 py-14 text-center"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-700"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" class="size-6" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01" /></svg></span><h3 class="mt-3 text-base font-bold text-slate-900">{{ request()->filled('search') || $statusFilter !== 'all' ? 'No matching assignments' : 'No tickets assigned yet' }}</h3><p class="mt-1 text-sm text-slate-500">{{ request()->filled('search') || $statusFilter !== 'all' ? 'Try another search or clear the selected queue.' : 'New work assigned to you will appear here.' }}</p>@if (request()->filled('search') || $statusFilter !== 'all')<a href="{{ route('technician.tickets.index') }}" class="mt-4 inline-flex ui-button-secondary">Clear filters</a>@endif</div>
    @else
        <div class="hidden overflow-x-auto lg:block"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500"><tr><th class="px-6 py-3">Ticket</th><th class="px-4 py-3">Employee</th><th class="px-4 py-3">Priority / category</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Assigned</th><th class="px-6 py-3 text-right">Updated</th></tr></thead><tbody class="divide-y divide-slate-100">
            @foreach ($tickets as $ticket)
                @php($currentReports = $ticket->currentAssignment?->workReports ?? collect())
                @php($latestReport = $currentReports->first())
                @php($sentBack = $currentReports->contains(fn ($report) => $report->review_status === \App\Enums\TechnicianWorkReviewStatus::ChangesRequested))
                <tr class="group transition hover:bg-indigo-50/35"><td class="px-6 py-4"><a href="{{ route('tickets.show', $ticket) }}" class="font-bold text-slate-900 transition group-hover:text-indigo-700">{{ $ticket->title }}</a><p class="mt-1 text-xs font-medium text-slate-500">{{ $ticket->ticket_number }}</p><div class="mt-2 flex flex-wrap gap-1.5">@if ($ticket->status->slug === \App\Enums\TicketStatusSlug::WaitingForUser->value)<span class="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-bold text-amber-800">Information requested</span>@endif @if ($ticket->status->slug === \App\Enums\TicketStatusSlug::ItSupportReview->value)<span class="rounded-full bg-cyan-50 px-2 py-0.5 text-[10px] font-bold text-cyan-800">Awaiting IT Support review</span>@endif @if ($sentBack)<span class="rounded-full bg-rose-50 px-2 py-0.5 text-[10px] font-bold text-rose-800">Sent back by IT Support</span>@endif</div></td><td class="px-4 py-4"><p class="font-semibold text-slate-800">{{ $ticket->user->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $ticket->department->name }}</p></td><td class="px-4 py-4"><x-ticket-priority-badge :priority="$ticket->priority" /><p class="mt-2 text-xs text-slate-500">{{ $ticket->category->name }}</p></td><td class="px-4 py-4"><x-ticket-status-badge :status="$ticket->status" /></td><td class="whitespace-nowrap px-4 py-4 text-xs text-slate-600">{{ $ticket->currentAssignment?->assigned_at?->format('M j, Y') ?? '—' }}<p class="mt-1 text-slate-400">{{ $latestReport?->work_started_at ? 'Started '.$latestReport->work_started_at->format('M j, g:i A') : 'Not started' }}</p></td><td class="whitespace-nowrap px-6 py-4 text-right"><time class="text-xs text-slate-500" datetime="{{ $ticket->updated_at->toIso8601String() }}">{{ $ticket->updated_at->diffForHumans() }}</time><a href="{{ route('tickets.show', $ticket) }}" class="mt-2 block text-xs font-bold text-indigo-700 transition hover:text-indigo-950">Open ticket <span aria-hidden="true">→</span></a></td></tr>
            @endforeach
        </tbody></table></div>
        <ul class="divide-y divide-slate-100 lg:hidden">
            @foreach ($tickets as $ticket)
                @php($currentReports = $ticket->currentAssignment?->workReports ?? collect())
                @php($sentBack = $currentReports->contains(fn ($report) => $report->review_status === \App\Enums\TechnicianWorkReviewStatus::ChangesRequested))
                <li class="p-4 sm:p-5"><a href="{{ route('tickets.show', $ticket) }}" class="block rounded-xl focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate font-bold text-slate-900">{{ $ticket->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $ticket->ticket_number }} · {{ $ticket->user->name }}</p></div><x-ticket-status-badge :status="$ticket->status" /></div><div class="mt-3 flex flex-wrap items-center gap-2"><x-ticket-priority-badge :priority="$ticket->priority" /><span class="text-xs text-slate-500">{{ $ticket->category->name }}</span>@if ($ticket->status->slug === \App\Enums\TicketStatusSlug::WaitingForUser->value)<span class="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-800">Waiting for employee</span>@endif @if ($sentBack)<span class="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-bold text-rose-800">Sent back</span>@endif</div><p class="mt-3 text-xs text-slate-500">Assigned {{ $ticket->currentAssignment?->assigned_at?->format('M j, Y') ?? '—' }} · Updated {{ $ticket->updated_at->diffForHumans() }}</p></a></li>
            @endforeach
        </ul>
        <div class="border-t border-slate-100 px-4 py-4 sm:px-6">{{ $tickets->links() }}</div>
    @endif
</section>
