@extends('layouts.app')

@section('title', 'Admin dashboard')
@section('topline', 'Administration overview')

@section('content')
    @php($allTickets = max(1, $statusCounts->sum()))
    <section class="ui-page-hero mb-7 flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p class="text-xs font-bold uppercase tracking-[.17em] text-violet-200">ServiceDesk operations</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-white sm:text-[2.65rem]">Administration overview</h1><p class="mt-3 text-sm leading-6 text-indigo-100/75">Current account activity, ticket workload, and service configuration.</p></div><a href="{{ route('admin.reports.index') }}" class="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-indigo-800 shadow-lg shadow-slate-950/10 transition hover:-translate-y-0.5 hover:bg-violet-50">Reports & analytics <span aria-hidden="true">→</span></a></section>

    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="ServiceDesk statistics">
        @foreach ([['Total users', $totalUsers, 'M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2 M10 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8'], ['Active employees', $activeEmployees, 'M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2 M10 11a4 4 0 1 0 0-8'], ['Active IT Support', $activeSupport, 'M12 8v4l3 2 M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20'], ['Open tickets', $statusCounts[\App\Enums\TicketStatusSlug::Open->value], 'M4 4h16v16H4z M8 9h8 M8 13h5'], ['In Progress', $statusCounts[\App\Enums\TicketStatusSlug::InProgress->value], 'M3 12h4l3-8 4 16 3-8h4'], ['Waiting for User', $statusCounts[\App\Enums\TicketStatusSlug::WaitingForUser->value], 'M12 8v4l3 2 M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20'], ['Resolved', $statusCounts[\App\Enums\TicketStatusSlug::Resolved->value], 'M5 12l4 4L19 6'], ['Closed', $statusCounts[\App\Enums\TicketStatusSlug::Closed->value], 'M6 6l12 12M18 6 6 18'], ['High / Critical', $highPriorityCount, 'm12 3 2.4 5 5.6.8-4 3.9.9 5.5-4.9-2.6L7.1 18.2l.9-5.5-4-3.9 5.6-.8z']] as [$label, $value, $icon])
            <article class="ui-stat-card"><div class="flex items-start justify-between gap-3"><p class="ui-stat-label">{{ $label }}</p><span class="ui-icon-tile size-9" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" class="size-[18px]"><path d="{{ $icon }}" /></svg></span></div><p class="ui-stat-value">{{ number_format($value) }}</p></article>
        @endforeach
    </section>

    <section class="ui-card mt-5 p-5 sm:p-6" aria-labelledby="admin-workload-heading"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="ui-eyebrow">Live workload</p><h2 id="admin-workload-heading" class="mt-1 text-lg font-bold text-slate-950">Tickets across the workflow</h2><p class="mt-1 text-sm text-slate-500">Distribution based on current ticket status.</p></div><span class="rounded-xl bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-800">{{ number_format($statusCounts->sum()) }} total tickets</span></div>
        <div class="mt-5 flex h-3 overflow-hidden rounded-full bg-slate-100" role="img" aria-label="Ticket distribution by workflow status">@foreach ($statuses as $status)@php($count = $statusCounts[$status->slug] ?? 0)@php($statusColor = \App\Enums\TicketStatusSlug::tryFrom($status->slug)?->color() ?? '#64748b')@if ($count > 0)<span class="h-full" style="background-color: {{ $statusColor }}; width: {{ round(($count / $allTickets) * 100, 2) }}%" title="{{ $status->name }}: {{ $count }}"></span>@endif @endforeach</div>
        <div class="mt-5 grid gap-x-8 gap-y-4 sm:grid-cols-2 xl:grid-cols-3">@foreach ($statuses as $status)@php($count = $statusCounts[$status->slug] ?? 0)@php($ratio = (int) round(($count / max(1, $statusCounts->max())) * 100))@php($statusColor = \App\Enums\TicketStatusSlug::tryFrom($status->slug)?->color() ?? '#64748b')<div><div class="mb-2 flex items-center justify-between gap-3 text-sm"><span class="inline-flex items-center gap-2 font-medium text-slate-700"><span class="size-2 rounded-full" style="background-color: {{ $statusColor }}"></span>{{ $status->name }}</span><span class="font-bold tabular-nums text-slate-900">{{ number_format($count) }}</span></div><span class="ui-chart-track block"><span class="ui-chart-fill block" style="width: {{ $ratio }}%"></span></span></div>@endforeach</div>
    </section>

    <div class="mt-5 grid gap-5 xl:grid-cols-2">
        <section class="ui-card overflow-hidden"><div class="flex items-center justify-between gap-4 border-b border-slate-100 bg-gradient-to-r from-white to-indigo-50/45 px-5 py-5"><div><p class="ui-eyebrow">Latest requests</p><h2 class="mt-1 text-lg font-bold text-slate-950">Recent tickets</h2></div><a href="{{ route('tickets.index') }}" class="ui-button-secondary">All tickets</a></div>
            @forelse ($recentTickets as $ticket)<a href="{{ route('tickets.show', $ticket) }}" class="group flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 last:border-0 transition hover:bg-violet-50/45"><span class="min-w-0"><span class="block font-mono text-[11px] font-semibold text-violet-700">{{ $ticket->ticket_number }}</span><span class="mt-1 block truncate text-sm font-semibold text-slate-900 group-hover:text-violet-800">{{ $ticket->title }}</span><span class="mt-1 block text-xs text-slate-500">{{ $ticket->user->name }} · {{ $ticket->department->name }}</span></span><span class="shrink-0 text-right"><x-ticket-status-badge :status="$ticket->status" /><span class="mt-1 block text-xs text-slate-500">{{ $ticket->created_at->format('M j, Y') }}</span></span></a>
            @empty<div class="ui-empty m-4"><p class="text-sm font-semibold text-slate-800">No tickets yet</p></div>@endforelse
        </section>
        <section class="ui-card overflow-hidden"><div class="flex items-center justify-between gap-4 border-b border-slate-100 bg-gradient-to-r from-white to-violet-50/45 px-5 py-5"><div><p class="ui-eyebrow">Directory updates</p><h2 class="mt-1 text-lg font-bold text-slate-950">Recent account activity</h2></div><a href="{{ route('admin.users.index') }}" class="ui-button-secondary">Manage users</a></div>
            @forelse ($recentUsers as $user)<a href="{{ route('admin.users.show', $user) }}" class="group flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 last:border-0 transition hover:bg-violet-50/45"><span class="flex min-w-0 items-center gap-3"><span class="grid size-9 shrink-0 place-items-center rounded-full bg-gradient-to-br from-indigo-100 to-violet-100 text-xs font-bold text-indigo-800">{{ $user->initials }}</span><span class="min-w-0"><span class="block truncate text-sm font-semibold text-slate-900 group-hover:text-violet-800">{{ $user->name }}</span><span class="mt-1 block truncate text-xs text-slate-500">{{ $user->role->label() }}{{ $user->department ? ' · '.$user->department->name : '' }}</span></span></span><span class="shrink-0 text-xs text-slate-500">{{ $user->updated_at->diffForHumans() }}</span></a>
            @empty<div class="ui-empty m-4"><p class="text-sm font-semibold text-slate-800">No users found</p></div>@endforelse
        </section>
    </div>

    <div class="mt-5 grid gap-5 lg:grid-cols-2"><section class="ui-card p-5 sm:p-6"><p class="ui-eyebrow">Configuration</p><h2 class="mt-1 text-lg font-bold text-slate-950">Ticket workflow</h2><div class="mt-4 grid gap-2 sm:grid-cols-2">@foreach ($statuses as $status)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/70 px-3 py-3"><span class="text-sm font-medium text-slate-700">{{ $status->name }}</span><span class="rounded-full px-2 py-1 text-[10px] font-bold {{ $status->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-600' }}">{{ $status->is_active ? 'ACTIVE' : 'INACTIVE' }}</span></div>@endforeach</div><a href="{{ route('admin.statuses.index') }}" class="mt-4 inline-flex text-sm font-semibold text-violet-700 hover:text-violet-900">View workflow setup →</a></section>
        <section class="ui-card p-5 sm:p-6"><p class="ui-eyebrow">Service targets</p><h2 class="mt-1 text-lg font-bold text-slate-950">Priority & SLA levels</h2><div class="mt-4 grid gap-2 sm:grid-cols-2">@foreach ($priorities as $priority)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/70 px-3 py-3"><span class="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><span class="size-2.5 rounded-full" style="background-color: {{ $priority->color }}"></span>{{ $priority->name }}</span><span class="text-xs font-semibold text-slate-500">Level {{ $priority->level }}</span></div>@endforeach</div><a href="{{ route('admin.priorities.index') }}" class="mt-4 inline-flex text-sm font-semibold text-violet-700 hover:text-violet-900">Manage priority targets →</a></section></div>
@endsection
