@extends('layouts.app')
@section('title', 'Reports')
@section('topline', 'Operational reports')
@section('content')
    <div class="ui-page-toolbar mb-6 flex flex-wrap items-center justify-between gap-4"><div><p class="ui-eyebrow">Operational insight</p><h1 class="ui-page-title">Ticket reports</h1><p class="mt-2 text-sm text-slate-500">Aggregated ticket data; requester contact details and descriptions are excluded.</p></div><a href="{{ route('admin.reports.export', $filters) }}" class="ui-button-secondary">Download CSV <span aria-hidden="true">↓</span></a></div>
    <form method="GET" action="{{ route('admin.reports.index') }}" class="mb-6 grid gap-3 ui-card p-4 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-end sm:p-5"><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Created from</span><input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="w-full text-sm"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Created to</span><input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="w-full text-sm"></label><button class="ui-button-primary">Apply dates</button><a href="{{ route('admin.reports.index') }}" class="ui-button-secondary">Clear</a></form>
    <section class="mb-6"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="ui-stat-card"><div class="flex items-center justify-between gap-3"><p class="ui-stat-label">Tickets within SLA</p><span class="ui-icon-tile bg-emerald-50 text-emerald-700 ring-emerald-100"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="m5 12 4 4L19 6"/></svg></span></div><p class="ui-stat-value">{{ number_format($slaMetrics['within_sla']) }}</p></article><article class="ui-stat-card"><div class="flex items-center justify-between gap-3"><p class="ui-stat-label">Overdue / breached</p><span class="ui-icon-tile bg-rose-50 text-rose-700 ring-rose-100"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v4m0 4h.01M10.3 3.9 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3l-7.5-13.1a2 2 0 0 0-3.4 0Z"/></svg></span></div><p class="relative z-10 mt-3 text-3xl font-bold tracking-tight text-rose-700">{{ number_format($slaMetrics['overdue']) }}</p></article><article class="ui-stat-card"><div class="flex items-center justify-between gap-3"><p class="ui-stat-label">SLA compliance</p><span class="ui-icon-tile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M4 18V9m5 9V5m5 13v-6m5 6V3"/></svg></span></div><p class="ui-stat-value">{{ number_format($slaMetrics['compliance'], 1) }}%</p></article><article class="ui-stat-card"><div class="flex items-center justify-between gap-3"><p class="ui-stat-label">Tickets in range</p><span class="ui-icon-tile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M7 3v3m10-3v3M4 9h16M5 5h14a1 1 0 0 1 1 1v13H4V6a1 1 0 0 1 1-1Z"/></svg></span></div><p class="ui-stat-value">{{ number_format($slaMetrics['total']) }}</p></article></div>
        <div class="mt-4 grid gap-4 md:grid-cols-2"><article class="ui-card p-5 sm:p-6"><div class="flex items-center gap-3"><span class="ui-icon-tile bg-rose-50 text-rose-700 ring-rose-100"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="m12 3 2.4 5 5.6.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.6-.8L12 3Z"/></svg></span><h2 class="font-bold text-slate-950">Overdue by priority</h2></div>@php($maxOverduePriority = max(1, max($slaMetrics['overdue_by_priority'] ?: [0])))@forelse ($slaMetrics['overdue_by_priority'] as $priority => $count)<div class="mt-4"><div class="mb-1.5 flex justify-between gap-3 text-sm"><span class="text-slate-600">{{ $priority }}</span><span class="font-bold tabular-nums text-slate-900">{{ number_format($count) }}</span></div><div class="ui-chart-track"><div class="h-full rounded-full bg-gradient-to-r from-rose-400 to-orange-400" style="width: {{ round(($count / $maxOverduePriority) * 100) }}%"></div></div></div>@empty<div class="ui-empty mt-4 py-6"><p class="text-sm font-semibold text-slate-800">No overdue tickets</p></div>@endforelse</article><article class="ui-card p-5 sm:p-6"><div class="flex items-center gap-3"><span class="ui-icon-tile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2m6-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8 1v5m3-2.5h-6"/></svg></span><h2 class="font-bold text-slate-950">Overdue by current support agent</h2></div>@php($maxOverdueAgent = max(1, max($slaMetrics['overdue_by_agent'] ?: [0])))@forelse ($slaMetrics['overdue_by_agent'] as $agent => $count)<div class="mt-4"><div class="mb-1.5 flex justify-between gap-3 text-sm"><span class="truncate text-slate-600">{{ $agent }}</span><span class="font-bold tabular-nums text-slate-900">{{ number_format($count) }}</span></div><div class="ui-chart-track"><div class="ui-chart-fill" style="width: {{ round(($count / $maxOverdueAgent) * 100) }}%"></div></div></div>@empty<div class="ui-empty mt-4 py-6"><p class="text-sm font-semibold text-slate-800">No overdue tickets</p></div>@endforelse</article></div>
    </section>
    <div class="grid gap-6 xl:grid-cols-2">
        @foreach ([['Tickets by status', $byStatus], ['Tickets by priority', $byPriority], ['Tickets by category', $byCategory], ['Tickets by department', $byDepartment], ['Tickets by current support agent', $byAgent], ['Tickets created over time', $overTime]] as [$heading, $rows])
            <section class="ui-card p-5 sm:p-6"><div class="flex items-center gap-3"><span class="ui-icon-tile" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" class="size-5"><path d="M3 3v18h18 M8 15v-3 M13 15V6 M18 15V9" /></svg></span><h2 class="text-base font-bold text-slate-950">{{ $heading }}</h2></div>@if ($rows->isEmpty())<p class="ui-empty mt-4 py-8 text-sm text-slate-500">No ticket data for this date range.</p>@else<div class="mt-5 space-y-4">@foreach ($rows as $row)<div><div class="mb-1.5 flex justify-between gap-4 text-sm"><span class="truncate font-medium text-slate-700">{{ $row->label ?: 'Unassigned' }}</span><span class="font-bold tabular-nums text-slate-900">{{ number_format($row->total) }}</span></div><div class="ui-chart-track"><div class="ui-chart-fill transition-[width] duration-500" style="width: {{ max(2, min(100, (int) round(($row->total / max(1, $rows->max('total'))) * 100))) }}%"></div></div></div>@endforeach</div>@endif</section>
        @endforeach
    </div>
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <section class="ui-card overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">Open high-priority summary</h2><p class="mt-1 text-xs text-slate-500">High and critical tickets created within the selected range</p></div>@forelse ($highPriorityOpen as $ticket)<div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-3 last:border-0"><span><span class="block font-mono text-xs text-slate-500">{{ $ticket->ticket_number }}</span><span class="mt-1 block text-sm font-semibold text-slate-900">{{ $ticket->title }}</span></span><span class="text-right text-xs text-slate-600">{{ $ticket->priority }} · {{ $ticket->status }}<span class="mt-1 block">{{ $ticket->department }}</span></span></div>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">No open high-priority tickets in this range.</p>@endforelse</section>
        <section class="ui-card overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">Recently resolved or closed</h2><p class="mt-1 text-xs text-slate-500">Latest completed tickets created within the selected range</p></div>@forelse ($recentlyClosed as $ticket)<div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-3 last:border-0"><span><span class="block font-mono text-xs text-slate-500">{{ $ticket->ticket_number }}</span><span class="mt-1 block text-sm font-semibold text-slate-900">{{ $ticket->title }}</span></span><span class="text-right text-xs text-slate-600">{{ $ticket->status }}<span class="mt-1 block">{{ $ticket->closed_at ?: $ticket->resolved_at }}</span></span></div>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">No completed tickets in this range.</p>@endforelse</section>
    </div>
    @if ($errors->has('to'))<p class="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{{ $errors->first('to') }}</p>@endif
@endsection
