@extends('layouts.app')
@section('title', 'Reports')
@section('topline', 'Operational reports')
@section('content')
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-700">Operational insight</p><h1 class="mt-1 text-2xl font-bold text-slate-950">Ticket reports</h1><p class="mt-1 text-sm text-slate-500">Aggregated ticket data; requester contact details and descriptions are excluded.</p></div><a href="{{ route('admin.reports.export', $filters) }}" class="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Export CSV</a></div>
    <form method="GET" action="{{ route('admin.reports.index') }}" class="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_1fr_auto_auto] sm:items-end"><label><span class="mb-1 block text-xs font-semibold text-slate-600">Created from</span><input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="w-full rounded-lg border-slate-300 text-sm"></label><label><span class="mb-1 block text-xs font-semibold text-slate-600">Created to</span><input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="w-full rounded-lg border-slate-300 text-sm"></label><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Apply dates</button><a href="{{ route('admin.reports.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700">Clear</a></form>
    <section class="mb-6"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Tickets within SLA</p><p class="mt-2 text-3xl font-bold text-slate-950">{{ number_format($slaMetrics['within_sla']) }}</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Overdue / breached</p><p class="mt-2 text-3xl font-bold text-rose-700">{{ number_format($slaMetrics['overdue']) }}</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">SLA compliance</p><p class="mt-2 text-3xl font-bold text-slate-950">{{ number_format($slaMetrics['compliance'], 1) }}%</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Tickets in range</p><p class="mt-2 text-3xl font-bold text-slate-950">{{ number_format($slaMetrics['total']) }}</p></article></div>
        <div class="mt-4 grid gap-4 md:grid-cols-2"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Overdue by priority</h2>@forelse ($slaMetrics['overdue_by_priority'] as $priority => $count)<p class="mt-3 flex justify-between text-sm"><span class="text-slate-600">{{ $priority }}</span><span class="font-semibold text-slate-900">{{ number_format($count) }}</span></p>@empty<p class="mt-3 text-sm text-slate-500">No overdue tickets.</p>@endforelse</article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Overdue by current support agent</h2>@forelse ($slaMetrics['overdue_by_agent'] as $agent => $count)<p class="mt-3 flex justify-between text-sm"><span class="text-slate-600">{{ $agent }}</span><span class="font-semibold text-slate-900">{{ number_format($count) }}</span></p>@empty<p class="mt-3 text-sm text-slate-500">No overdue tickets.</p>@endforelse</article></div>
    </section>
    <div class="grid gap-6 xl:grid-cols-2">
        @foreach ([['Tickets by status', $byStatus], ['Tickets by priority', $byPriority], ['Tickets by category', $byCategory], ['Tickets by department', $byDepartment], ['Tickets by current support agent', $byAgent], ['Tickets created over time', $overTime]] as [$heading, $rows])
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">{{ $heading }}</h2>@if ($rows->isEmpty())<p class="mt-4 rounded-lg bg-slate-50 px-4 py-6 text-center text-sm text-slate-500">No ticket data for this date range.</p>@else<div class="mt-4 space-y-3">@foreach ($rows as $row)<div><div class="mb-1 flex justify-between gap-4 text-sm"><span class="truncate text-slate-700">{{ $row->label ?: 'Unassigned' }}</span><span class="font-semibold tabular-nums text-slate-900">{{ number_format($row->total) }}</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-500" style="width: {{ max(2, min(100, (int) round(($row->total / max(1, $rows->max('total'))) * 100))) }}%"></div></div></div>@endforeach</div>@endif</section>
        @endforeach
    </div>
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">Open high-priority summary</h2><p class="mt-1 text-xs text-slate-500">High and critical tickets created within the selected range</p></div>@forelse ($highPriorityOpen as $ticket)<div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-3 last:border-0"><span><span class="block font-mono text-xs text-slate-500">{{ $ticket->ticket_number }}</span><span class="mt-1 block text-sm font-semibold text-slate-900">{{ $ticket->title }}</span></span><span class="text-right text-xs text-slate-600">{{ $ticket->priority }} · {{ $ticket->status }}<span class="mt-1 block">{{ $ticket->department }}</span></span></div>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">No open high-priority tickets in this range.</p>@endforelse</section>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">Recently resolved or closed</h2><p class="mt-1 text-xs text-slate-500">Latest completed tickets created within the selected range</p></div>@forelse ($recentlyClosed as $ticket)<div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-3 last:border-0"><span><span class="block font-mono text-xs text-slate-500">{{ $ticket->ticket_number }}</span><span class="mt-1 block text-sm font-semibold text-slate-900">{{ $ticket->title }}</span></span><span class="text-right text-xs text-slate-600">{{ $ticket->status }}<span class="mt-1 block">{{ $ticket->closed_at ?: $ticket->resolved_at }}</span></span></div>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">No completed tickets in this range.</p>@endforelse</section>
    </div>
    @if ($errors->has('to'))<p class="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{{ $errors->first('to') }}</p>@endif
@endsection
