@extends('layouts.app')

@section('title', $ticket->ticket_number)
@section('topline', 'Technician ticket detail')

@section('content')
    @php
        $status = \App\Enums\TicketStatusSlug::tryFrom($ticket->status->slug);
        $sentBack = $latestReport?->review_status === \App\Enums\TechnicianWorkReviewStatus::ChangesRequested;
        $activeWork = $ticket->status->slug === \App\Enums\TicketStatusSlug::InProgress->value
            && $latestReport?->work_started_at !== null
            && $latestReport?->work_completed_at === null
            && $latestReport?->review_status === \App\Enums\TechnicianWorkReviewStatus::Pending;
        $canStart = $ticket->status->slug === \App\Enums\TicketStatusSlug::Assigned->value && $latestReport === null;
        $canResume = $sentBack && $ticket->status->slug === \App\Enums\TicketStatusSlug::InProgress->value;
        $workflowNotice = match (request()->query('workflow_notice')) {
            'work_started' => 'Work started. The ticket is now in progress.',
            'information_requested' => 'Your request was sent to the employee.',
            'work_completed' => 'Your work report was submitted for IT Support review.',
            default => null,
        };
    @endphp

    @if ($workflowNotice)<div class="ui-alert-success mb-5" role="status">{{ $workflowNotice }}</div>@endif

    <section class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
        <div><a href="{{ route('technician.tickets.index') }}" class="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-700 transition hover:text-indigo-950">← Assigned tickets</a><div class="mt-3 flex flex-wrap items-center gap-2"><span class="rounded-lg bg-slate-100 px-2.5 py-1.5 font-mono text-xs font-bold text-slate-700">{{ $ticket->ticket_number }}</span><x-ticket-status-badge :status="$ticket->status" /><x-ticket-priority-badge :priority="$ticket->priority" /></div><h1 class="mt-3 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{{ $ticket->title }}</h1><p class="mt-2 text-sm text-slate-500">Submitted {{ $ticket->created_at->format('M j, Y g:i A') }} · Updated {{ $ticket->updated_at->diffForHumans() }}</p></div>
        @if ($ticket->status->slug === \App\Enums\TicketStatusSlug::ItSupportReview->value)<span class="inline-flex items-center gap-2 self-start rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-3 text-sm font-bold text-cyan-900"><span class="size-2 rounded-full bg-cyan-500" aria-hidden="true"></span>Waiting for IT Support Review</span>@elseif ($ticket->status->slug === \App\Enums\TicketStatusSlug::Closed->value)<span class="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-slate-100 px-4 py-3 text-sm font-bold text-slate-700">Ticket closed</span>@endif
    </section>

    @if ($sentBack)
        <section class="mb-6 overflow-hidden rounded-2xl border border-rose-200 bg-gradient-to-r from-rose-50 via-white to-orange-50 shadow-sm" aria-labelledby="work-sent-back-heading"><div class="flex items-start gap-3 p-5 sm:p-6"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-rose-100 text-rose-700"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M4 7h11a5 5 0 0 1 0 10H8m0 0 4-4m-4 4 4 4" /></svg></span><div class="min-w-0"><h2 id="work-sent-back-heading" class="text-base font-bold text-rose-950">Work Sent Back by IT Support</h2><p class="mt-1 text-sm text-rose-800">Please review the feedback below, continue the technical work, and submit an updated report.</p><blockquote class="mt-4 rounded-xl border border-rose-200/80 bg-white/80 px-4 py-3 text-sm leading-6 text-slate-800">{{ $latestReport->review_note ?: 'IT Support requested additional work.' }}</blockquote><p class="mt-2 text-xs text-slate-500">Reviewed by {{ $latestReport->reviewer?->name ?? 'IT Support' }}@if ($latestReport->reviewed_at) · {{ $latestReport->reviewed_at->format('M j, Y g:i A') }}@endif</p></div></div></section>
    @endif

    @if ($technicianInformationRequest)
        <section class="mb-6 rounded-2xl border border-amber-200 bg-amber-50/80 p-5 sm:p-6" aria-labelledby="information-pending-heading"><div class="flex items-start gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-800"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M10.3 3.9 2.8 17a2 2 0 0 0 1.7 3h15a2 2 0 0 0 1.7-3l-7.5-13.1a2 2 0 0 0-3.4 0Z" /></svg></span><div><h2 id="information-pending-heading" class="font-bold text-amber-950">Waiting for Employee Information</h2><p class="mt-2 whitespace-pre-line text-sm leading-6 text-amber-950">{{ $technicianInformationRequest->body }}</p><p class="mt-2 text-xs text-amber-800">Requested {{ $technicianInformationRequest->created_at->format('M j, Y g:i A') }} · Employee replies will appear in the conversation below.</p></div></div></section>
    @endif

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_21rem]">
        <div class="min-w-0 space-y-6">
            <article class="ui-card overflow-hidden">
                <div class="border-b border-slate-100 bg-gradient-to-r from-indigo-50/70 via-white to-violet-50/50 p-5 sm:p-7"><div class="flex items-start gap-3"><span class="ui-icon-tile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01" /></svg></span><div><p class="ui-eyebrow">Request summary</p><h2 class="mt-1 text-lg font-bold text-slate-950">Ticket details</h2></div></div><p class="mt-5 whitespace-pre-line text-sm leading-7 text-slate-700">{{ $ticket->description }}</p></div>
                <div class="grid gap-4 p-5 sm:grid-cols-2 sm:p-6"><div class="rounded-xl border border-slate-100 bg-slate-50/70 p-4"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-500">Employee / requester</p><p class="mt-1.5 font-semibold text-slate-900">{{ $ticket->user->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $ticket->department->name }} department</p></div><div class="rounded-xl border border-slate-100 bg-slate-50/70 p-4"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-500">Assigned to you</p><p class="mt-1.5 font-semibold text-slate-900">{{ $ticket->currentAssignment?->assignee?->name ?? auth()->user()->name }}</p><p class="mt-1 text-xs text-slate-500">Assigned by {{ $ticket->currentAssignment?->assigner?->name ?? 'IT Support' }}@if ($ticket->currentAssignment?->assigned_at) · {{ $ticket->currentAssignment->assigned_at->format('M j, Y g:i A') }}@endif</p></div></div>
            </article>

            <section class="ui-card overflow-hidden" aria-labelledby="technician-work-heading">
                <div class="ui-panel-heading"><span class="ui-icon-tile" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M14.7 6.3a4 4 0 0 0-5 5L4 17v3h3l5.7-5.7a4 4 0 0 0 5-5L15 12l-3-3 2.7-2.7Z" /></svg></span><div><h2 id="technician-work-heading" class="text-lg font-bold text-slate-950">Technician Work Report</h2><p class="mt-1 text-sm text-slate-500">Record investigation and technical work for IT Support review.</p></div></div>

                @if ($workReports->isEmpty())
                    <div class="border-b border-slate-100 px-5 py-5 sm:px-7"><div class="rounded-xl border border-dashed border-slate-300 bg-slate-50/70 p-4 text-sm text-slate-600">No work has been recorded for this assignment yet. Start work to create its first report.</div></div>
                @else
                    <div class="space-y-4 border-b border-slate-100 p-5 sm:p-7">
                        @foreach ($workReports as $report)
                            <article class="rounded-2xl border {{ $loop->first ? 'border-indigo-200 bg-indigo-50/35' : 'border-slate-200 bg-white' }} p-4 sm:p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm font-bold text-slate-900">{{ $loop->first ? 'Latest work report' : 'Previous work report' }}</p><p class="mt-1 text-xs text-slate-500">Started {{ $report->work_started_at?->format('M j, Y g:i A') ?? '—' }}@if ($report->startedBy) by {{ $report->startedBy->name }}@endif</p></div>@if ($report->review_status)<span @class(['rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide', 'bg-cyan-100 text-cyan-900' => $report->review_status === \App\Enums\TechnicianWorkReviewStatus::Pending && $report->work_completed_at, 'bg-emerald-100 text-emerald-900' => $report->review_status === \App\Enums\TechnicianWorkReviewStatus::Approved, 'bg-rose-100 text-rose-900' => $report->review_status === \App\Enums\TechnicianWorkReviewStatus::ChangesRequested, 'bg-indigo-100 text-indigo-900' => $report->review_status === \App\Enums\TechnicianWorkReviewStatus::Pending && ! $report->work_completed_at])>{{ $report->work_completed_at ? $report->review_status->label() : 'Work in progress' }}</span>@endif</div>
                                @if ($report->work_completed_at)<p class="mt-2 text-xs font-medium text-slate-500">Completed {{ $report->work_completed_at->format('M j, Y g:i A') }}</p>@endif
                                @if ($report->work_summary)<dl class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-xl bg-white/90 p-3.5"><dt class="text-[10px] font-bold uppercase tracking-wider text-slate-500">Work summary</dt><dd class="mt-1.5 whitespace-pre-line text-sm leading-6 text-slate-800">{{ $report->work_summary }}</dd></div><div class="rounded-xl bg-white/90 p-3.5"><dt class="text-[10px] font-bold uppercase tracking-wider text-slate-500">Root cause</dt><dd class="mt-1.5 whitespace-pre-line text-sm leading-6 text-slate-800">{{ $report->root_cause }}</dd></div></dl>@endif
                                @if ($report->technician_notes)<div class="mt-3 rounded-xl bg-white/90 p-3.5"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-500">Technician notes</p><p class="mt-1.5 whitespace-pre-line text-sm leading-6 text-slate-800">{{ $report->technician_notes }}</p></div>@endif
                                @if ($report->review_note && ! $loop->first)<div class="mt-3 rounded-xl border border-rose-100 bg-rose-50 p-3.5"><p class="text-[10px] font-bold uppercase tracking-wider text-rose-800">IT Support review note</p><p class="mt-1.5 whitespace-pre-line text-sm leading-6 text-rose-950">{{ $report->review_note }}</p>@if ($report->reviewed_at)<p class="mt-2 text-xs text-rose-800">{{ $report->reviewer?->name }} · {{ $report->reviewed_at->format('M j, Y g:i A') }}</p>@endif</div>@endif
                            </article>
                        @endforeach
                    </div>
                @endif

                @if ($canStart || $canResume)
                    <div class="bg-slate-50/80 p-5 sm:p-7"><div class="mb-4"><h3 class="font-bold text-slate-900">{{ $canResume ? 'Continue the requested work' : 'Ready to begin?' }}</h3><p class="mt-1 text-sm text-slate-500">{{ $canResume ? 'Starting again creates a new work report under this assignment.' : 'Start work to record the technician and start time.' }}</p></div><form method="POST" action="{{ route('tickets.work.start', $ticket) }}" data-async-workflow-form data-success-key="work_started" data-success-message="Work started successfully." data-loading-form>@csrf<div data-workflow-feedback class="mb-3 hidden rounded-xl px-3 py-2 text-sm" role="status"></div><button type="submit" data-loading-label="Starting work…" class="ui-button-primary">{{ $canResume ? 'Continue Work' : 'Start Work' }} <span aria-hidden="true">→</span></button></form></div>
                @elseif ($activeWork)
                    <div class="space-y-5 bg-slate-50/80 p-5 sm:p-7"><div class="flex items-center gap-3 rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-3"><span class="relative flex size-2.5"><span class="absolute inline-flex size-full animate-ping rounded-full bg-indigo-400 opacity-50 motion-reduce:animate-none"></span><span class="relative inline-flex size-2.5 rounded-full bg-indigo-600"></span></span><div><p class="text-sm font-bold text-indigo-950">Work In Progress</p><p class="mt-0.5 text-xs text-indigo-800">Started {{ $latestReport->work_started_at->format('M j, Y g:i A') }}</p></div></div>
                        <form method="POST" action="{{ route('tickets.work.request-information', $ticket) }}" class="rounded-2xl border border-amber-200 bg-white p-4 sm:p-5" data-async-workflow-form data-success-key="information_requested" data-success-message="Your request was sent to the employee." data-loading-form>@csrf<div data-workflow-feedback class="mb-3 hidden rounded-xl px-3 py-2 text-sm" role="status"></div><label for="employee-information-request" class="block text-sm font-bold text-slate-900">Request Information from Employee</label><p class="mt-1 text-xs leading-5 text-slate-500">The message is visible to the employee. Work pauses until they respond.</p><textarea id="employee-information-request" name="body" rows="3" maxlength="10000" required data-trim-required aria-describedby="information-request-error" placeholder="Explain what information or action you need…" class="mt-3 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-sm shadow-sm transition focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"></textarea><p id="information-request-error" data-field-error="body" class="mt-1 hidden text-sm font-medium text-rose-700"></p><div class="mt-3 flex justify-end"><button type="submit" data-loading-label="Sending request…" class="ui-button-secondary">Request information</button></div></form>
                        <form method="POST" action="{{ route('tickets.work.complete', $ticket) }}" class="rounded-2xl border border-emerald-200 bg-white p-4 sm:p-5" data-async-workflow-form data-success-key="work_completed" data-success-message="Your work report was submitted for IT Support review." data-confirm="Complete the technical work and submit this report to IT Support for review? You will not be able to change the workflow while it is under review." data-loading-form>@csrf<div data-workflow-feedback class="mb-3 hidden rounded-xl px-3 py-2 text-sm" role="status"></div><div><h3 class="text-sm font-bold text-slate-900">Complete Technical Work</h3><p class="mt-1 text-xs leading-5 text-slate-500">Submit the required report. IT Support reviews completed work and closes the ticket if approved.</p></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold text-slate-700">Work summary <span class="text-rose-500">*</span><textarea name="work_summary" rows="4" maxlength="20000" required data-trim-required class="mt-1.5 w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20" placeholder="What work did you perform?"></textarea><span data-field-error="work_summary" class="mt-1 hidden text-xs font-medium text-rose-700"></span></label><label class="block text-sm font-semibold text-slate-700">Root cause <span class="text-rose-500">*</span><textarea name="root_cause" rows="4" maxlength="20000" required data-trim-required class="mt-1.5 w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20" placeholder="What caused the issue?"></textarea><span data-field-error="root_cause" class="mt-1 hidden text-xs font-medium text-rose-700"></span></label></div><label class="mt-4 block text-sm font-semibold text-slate-700">Additional technician notes<textarea name="technician_notes" rows="3" maxlength="20000" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20" placeholder="Optional context for the IT Support reviewer"></textarea><span data-field-error="technician_notes" class="mt-1 hidden text-xs font-medium text-rose-700"></span></label><div class="mt-4 flex flex-col justify-between gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center"><p class="max-w-xl text-xs leading-5 text-slate-500">After submission, work is locked while IT Support reviews your report. You cannot approve or close the ticket.</p><button type="submit" data-loading-label="Submitting report…" class="ui-button-primary shrink-0 bg-emerald-600 hover:bg-emerald-700 focus-visible:outline-emerald-600">Complete Work and Submit Report <span aria-hidden="true">→</span></button></div></form>
                    </div>
                @elseif ($ticket->status->slug === \App\Enums\TicketStatusSlug::ItSupportReview->value)
                    <div class="border-t border-cyan-100 bg-cyan-50/70 p-5 sm:p-7"><p class="text-sm font-bold text-cyan-950">Waiting for IT Support Review</p><p class="mt-1 text-sm text-cyan-900">Your completed work and report are with IT Support. Workflow actions are disabled until the review is complete.</p></div>
                @elseif ($ticket->status->slug === \App\Enums\TicketStatusSlug::WaitingForUser->value)
                    <div class="border-t border-amber-100 bg-amber-50/70 p-5 sm:p-7"><p class="text-sm font-bold text-amber-950">Waiting for Employee Information</p><p class="mt-1 text-sm text-amber-900">Work actions are paused. You can continue after the employee replies; their response will appear in the conversation.</p></div>
                @elseif ($ticket->status->slug === \App\Enums\TicketStatusSlug::Closed->value || $ticket->status->slug === \App\Enums\TicketStatusSlug::Resolved->value)
                    <div class="border-t border-slate-100 bg-slate-50 p-5 sm:p-7"><p class="text-sm font-bold text-slate-900">{{ $ticket->status->name }}</p><p class="mt-1 text-sm text-slate-600">This ticket is no longer accepting Technician workflow changes.</p></div>
                @else
                    <div class="border-t border-slate-100 bg-slate-50 p-5 sm:p-7"><p class="text-sm font-semibold text-slate-700">Workflow actions are unavailable in the current ticket state.</p></div>
                @endif
            </section>

            <x-ticket-conversation :ticket="$ticket" :comments="$comments" :attachments="$attachments" />
        </div>

        <aside class="space-y-5"><x-ticket-sla :ticket="$ticket" :sla="$sla" /><section class="ui-card p-5 shadow-sm"><h2 class="font-bold text-slate-900">Ticket information</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-xs text-slate-500">Category</dt><dd class="font-medium text-slate-800">{{ $ticket->category->name }}</dd></div><div><dt class="text-xs text-slate-500">Department</dt><dd class="font-medium text-slate-800">{{ $ticket->department->name }}</dd></div><div><dt class="text-xs text-slate-500">Created</dt><dd class="font-medium text-slate-800">{{ $ticket->created_at->format('M j, Y g:i A') }}</dd></div><div><dt class="text-xs text-slate-500">Current status</dt><dd class="mt-1"><x-ticket-status-badge :status="$ticket->status" /></dd></div></dl></section>
            <section class="ui-card overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-900">Assignment information</h2><p class="mt-1 text-xs text-slate-500">Visible assignment history for your account.</p></div>@forelse ($assignments as $assignment)<div class="border-b border-slate-100 px-5 py-4 last:border-0"><div class="flex items-center justify-between gap-2"><p class="text-sm font-semibold text-slate-800">{{ $assignment->assignee->name }}</p><span class="rounded-full px-2 py-0.5 text-[10px] font-bold {{ $assignment->unassigned_at ? 'bg-slate-100 text-slate-600' : 'bg-emerald-50 text-emerald-800' }}">{{ $assignment->unassigned_at ? 'Previous' : 'Current' }}</span></div><p class="mt-1 text-xs text-slate-500">Assigned by {{ $assignment->assigner->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $assignment->assigned_at->format('M j, Y g:i A') }}</p>@if ($assignment->note)<p class="mt-2 rounded-lg bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-600">{{ $assignment->note }}</p>@endif</div>@empty<p class="px-5 py-4 text-sm text-slate-500">No assignment details available.</p>@endforelse</section>
        </aside>
    </div>
@endsection
