@extends('layouts.app')

@section('title', 'Tickets')
@section('topline', 'Ticket administration')

@section('content')
    <section class="ui-page-toolbar mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><p class="ui-eyebrow">Service operations</p><h1 class="ui-page-title text-3xl">All tickets</h1><p class="mt-2 text-sm text-slate-500">Search and review tickets across the organization.</p></div>
        <p class="rounded-xl bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-800">{{ $tickets->total() }} {{ Str::plural('ticket', $tickets->total()) }}</p>
    </section>

    <section class="ticket-filter-card mb-5 overflow-hidden rounded-xl border border-gray-100 bg-white shadow-md" aria-label="Search and filter tickets">
        <div class="mb-4 flex items-center gap-3 border-b border-gray-100 bg-indigo-50/50 px-4 pb-3 pt-3.5 sm:px-5"><span class="grid size-9 place-items-center rounded-xl bg-indigo-100 text-indigo-600" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M4 5h16l-6.5 7.5v5l-3 1.5v-6.5L4 5Z" /></svg></span><div><h2 class="text-sm font-bold text-slate-900">Filter tickets</h2><p class="mt-0.5 text-xs text-slate-500">Narrow the list to find the right request</p></div></div>
        <form method="GET" action="{{ route('tickets.index') }}" class="grid grid-cols-1 gap-4 px-4 pb-4 sm:grid-cols-2 sm:px-5 sm:pb-5 xl:grid-cols-4">
            <label class="sm:col-span-2 xl:col-span-4"><span class="mb-1.5 block text-[11px] font-bold uppercase tracking-wider text-gray-500">Search</span><input type="search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Ticket number, title, requester" class="w-full rounded-lg border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-700 shadow-sm transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 focus:outline-none"></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Status</span><select name="status" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="">All statuses</option>@foreach ($statuses as $status)<option value="{{ $status->slug }}" @selected(($filters['status'] ?? '') === $status->slug)>{{ $status->name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Priority</span><select name="priority_id" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="">All priorities</option>@foreach ($priorities as $priority)<option value="{{ $priority->id }}" @selected((string) ($filters['priority_id'] ?? '') === (string) $priority->id)>{{ $priority->name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Category</span><select name="category_id" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="">All categories</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) ($filters['category_id'] ?? '') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-500">Sort by</span><select name="sort" class="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 shadow-sm transition focus:border-purple-500 focus:ring-2 focus:ring-purple-500/20 focus:outline-none"><option value="newest" @selected(($filters['sort'] ?? 'newest') === 'newest')>Newest first</option><option value="oldest" @selected(($filters['sort'] ?? '') === 'oldest')>Oldest first</option><option value="updated" @selected(($filters['sort'] ?? '') === 'updated')>Recently updated</option><option value="priority" @selected(($filters['sort'] ?? '') === 'priority')>Highest priority</option></select></label>
            <div class="flex items-center justify-end gap-2 border-t border-sky-100 pt-4 sm:col-span-2 xl:col-span-4"><a href="{{ route('tickets.index') }}" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600 transition hover:bg-sky-50 hover:text-sky-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600">Clear</a><button type="submit" class="ticket-filter-submit rounded-lg px-4 py-2.5 text-sm font-semibold shadow-sm transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600">Apply filters</button></div>
        </form>
    </section>

    <section class="ui-card overflow-hidden">
        @if ($tickets->isEmpty())
            <div class="ui-empty m-4"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-white text-slate-500 shadow-sm" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M4 5h16M7 12h10m-7 7h4" /></svg></span><h2 class="mt-4 text-sm font-bold text-slate-900">No tickets match these filters</h2><p class="mt-1 text-sm text-slate-500">Try broadening your search or clearing the filters.</p><a href="{{ route('tickets.index') }}" class="mt-4 inline-flex ui-button-secondary">Clear filters</a></div>
        @else
            <div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="ui-table-head"><tr><th class="px-6 py-3">Ticket / requester</th><th class="px-4 py-3">Category</th><th class="px-4 py-3">Priority</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Updated</th><th class="px-6 py-3"><span class="sr-only">Open ticket</span></th></tr></thead><tbody class="divide-y divide-slate-100">
                @foreach ($tickets as $ticket)
                    <tr class="transition hover:bg-slate-50"><td class="px-6 py-4"><a href="{{ route('tickets.show', $ticket) }}" class="font-semibold text-slate-900 hover:text-indigo-700">{{ $ticket->ticket_number }} · {{ $ticket->title }}</a><span class="mt-1 block text-xs text-slate-500">{{ $ticket->user->name }}</span></td><td class="px-4 py-4 text-slate-600">{{ $ticket->category->name }}</td><td class="px-4 py-4"><x-ticket-priority-badge :priority="$ticket->priority" /></td><td class="px-4 py-4"><x-ticket-status-badge :status="$ticket->status" /></td><td class="whitespace-nowrap px-4 py-4 text-slate-500">{{ $ticket->updated_at->format('M j, Y') }}</td><td class="whitespace-nowrap px-6 py-4 text-right"><a href="{{ route('tickets.show', $ticket) }}" class="font-semibold text-indigo-700 hover:text-indigo-900">Open ticket <span aria-hidden="true">→</span></a></td></tr>
                @endforeach
            </tbody></table></div>
            <div class="border-t border-slate-100 px-4 py-4 sm:px-6">{{ $tickets->links() }}</div>
        @endif
    </section>
@endsection
