@extends('layouts.app')
@section('title', ($creating ? 'Create ' : 'Edit ').$title)
@section('topline', 'Configuration')
@section('content')
    <div class="ui-page-toolbar mb-6"><a href="{{ $kind === 'department' ? route('admin.departments.index') : route('admin.categories.index') }}" class="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-700 transition hover:text-violet-900">← Back to {{ $kind === 'department' ? 'departments' : 'categories' }}</a><div class="mt-3 flex items-start gap-3"><span class="ui-icon-tile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h10"/></svg></span><div><p class="ui-eyebrow">ServiceDesk configuration</p><h1 class="ui-page-title text-2xl">{{ $creating ? 'Create' : 'Edit' }} {{ strtolower($title) }}</h1><p class="mt-1 text-sm text-slate-500">Manage ticket classification and ownership options.</p></div></div></div>
    <div class="mx-auto max-w-2xl"><form method="POST" action="{{ $creating ? route($storeRoute) : route($storeRoute, $item) }}" class="ui-form-card">@csrf @unless($creating) @method('PATCH') @endunless
        <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Name</span><input name="name" required maxlength="100" value="{{ old('name', $item->name) }}" class="w-full rounded-lg border-slate-300 text-sm @error('name') border-rose-500 @enderror">@error('name')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Description</span><textarea name="description" rows="4" maxlength="2000" class="w-full rounded-lg border-slate-300 text-sm @error('description') border-rose-500 @enderror">{{ old('description', $item->description) }}</textarea>@error('description')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        @unless($creating)<label class="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $item->is_active)) class="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"><span><span class="block text-sm font-semibold text-slate-800">Active</span><span class="block text-xs text-slate-500">Keep this item available in new ticket forms.</span></span></label>@endunless
        @error('is_active')<span class="block text-xs text-rose-700">{{ $message }}</span>@enderror
        <div class="flex justify-end gap-2 border-t border-slate-100 pt-5"><a href="{{ $kind === 'department' ? route('admin.departments.index') : route('admin.categories.index') }}" class="ui-button-secondary">Cancel</a><button class="ui-button-primary">Save</button></div>
    </form></div>
@endsection
