@extends('layouts.app')
@section('title', $title)
@section('topline', 'Configuration')
@section('content')
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-700">ServiceDesk configuration</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ $title }}</h1><p class="mt-1 text-sm text-slate-500">Inactive records remain available to historical ticket records.</p></div><a href="{{ route($createRoute) }}" class="ui-button-primary">Add {{ strtolower($kind) }}</a></div>
    <form method="GET" class="mb-5 flex flex-col gap-3 ui-card p-4 shadow-sm sm:flex-row"><label class="flex-1"><span class="sr-only">Search {{ strtolower($title) }}</span><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search by name" class="w-full rounded-lg border-slate-300 text-sm"></label><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Search</button><a href="{{ url()->current() }}" class="rounded-lg border border-slate-300 px-4 py-2 text-center text-sm font-semibold text-slate-700">Clear</a></form>
    <section class="ui-card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="ui-table-head"><tr><th class="px-5 py-3">Name</th><th class="px-5 py-3">Description</th><th class="px-5 py-3">Related records</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse ($items as $item)<tr><td class="px-5 py-4 font-semibold text-slate-900">{{ $item->name }}</td><td class="max-w-sm px-5 py-4 text-slate-600">{{ \Illuminate\Support\Str::limit($item->description, 100) ?: '—' }}</td><td class="px-5 py-4 text-slate-600">{{ $kind === 'department' ? $item->users_count.' users · '.$item->tickets_count.' tickets' : $item->tickets_count.' tickets' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $item->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $item->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route($editRoute, $item) }}" class="font-semibold text-indigo-700">Edit</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-slate-500">No {{ strtolower($title) }} found.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $items->links() }}</div></section>
@endsection
