<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('tickets', function (Blueprint $table) {
            $table->id();

            // Format INC-YYYY-XXXXXX (15 chars). Generated by a concurrency-safe
            // service in a later phase — the UNIQUE constraint is the final safety net.
            $table->string('ticket_number', 20)->unique();

            // All parent references use RESTRICT: a ticket is a business record and
            // must never be destroyed or orphaned by deleting reference/master data.
            // (Reference tables use soft deletes, so restricted hard deletes are the guard.)

            // Requester.
            $table->foreignId('user_id')->constrained('users')->restrictOnDelete();
            // Requester's department captured at creation, so reports stay accurate
            // even if the user later moves department.
            $table->foreignId('department_id')->constrained('departments')->restrictOnDelete();
            $table->foreignId('category_id')->constrained('ticket_categories')->restrictOnDelete();
            $table->foreignId('priority_id')->constrained('ticket_priorities')->restrictOnDelete();
            $table->foreignId('status_id')->constrained('ticket_statuses')->restrictOnDelete();

            $table->string('title');
            $table->text('description');
            $table->text('resolution')->nullable();
            $table->timestamp('resolved_at')->nullable();
            $table->timestamp('closed_at')->nullable();
            $table->timestamps();

            // Indexes beyond the FK indexes created above (user_id, department_id,
            // category_id, priority_id):
            //  - (status_id, created_at): support queue "tickets in status X, newest first".
            //    Its leading column also serves as the status_id FK index.
            //  - created_at: date-range reporting and global "latest tickets" lists.
            $table->index(['status_id', 'created_at'], 'tickets_status_id_created_at_index');
            $table->index('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('tickets');
    }
};
