@extends('layouts.app')
@section('title', $creating ? 'Create user' : 'Edit user')
@section('topline', 'User management')
@section('content')
    <div class="ui-page-toolbar mb-6"><a href="{{ $creating ? route('admin.users.index') : route('admin.users.show', $user) }}" class="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-700 transition hover:text-violet-900">← Back to users</a><div class="mt-3 flex items-start gap-3"><span class="ui-icon-tile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2m6-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8-1v6m3-3h-6"/></svg></span><div><p class="ui-eyebrow">Administrator access</p><h1 class="ui-page-title text-2xl">{{ $creating ? 'Create user' : 'Edit user' }}</h1><p class="mt-1 text-sm text-slate-500">Role and department are validated together. Passwords are never shown after creation.</p></div></div></div>
    <div class="mx-auto max-w-3xl"><form method="POST" action="{{ $creating ? route('admin.users.store') : route('admin.users.update', $user) }}" class="ui-form-card">
            @csrf @unless($creating) @method('PATCH') @endunless
            <div class="grid gap-4 sm:grid-cols-2">
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Full name</span><input name="name" required maxlength="255" value="{{ old('name', $user->name) }}" class="w-full rounded-lg border-slate-300 text-sm @error('name') border-rose-500 @enderror">@error('name')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Email</span><input name="email" type="email" required maxlength="255" value="{{ old('email', $user->email) }}" class="w-full rounded-lg border-slate-300 text-sm @error('email') border-rose-500 @enderror">@error('email')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Employee ID</span><input name="employee_id" maxlength="50" value="{{ old('employee_id', $user->employee_id) }}" class="w-full rounded-lg border-slate-300 text-sm @error('employee_id') border-rose-500 @enderror">@error('employee_id')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Phone</span><input name="phone" maxlength="30" value="{{ old('phone', $user->phone) }}" class="w-full rounded-lg border-slate-300 text-sm @error('phone') border-rose-500 @enderror">@error('phone')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Role</span><select name="role" required @disabled(! $creating && auth()->user()->is($user)) class="w-full rounded-lg border-slate-300 text-sm @error('role') border-rose-500 @enderror">@foreach ($roles as $role)<option value="{{ $role->value }}" @selected(old('role', $user->role?->value ?? \App\Enums\UserRole::Employee->value) === $role->value)>{{ $role->label() }}</option>@endforeach</select>@error('role')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Department</span><select name="department_id" class="w-full rounded-lg border-slate-300 text-sm @error('department_id') border-rose-500 @enderror"><option value="">{{ 'No department (admin only)' }}</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected((string) old('department_id', $user->department_id) === (string) $department->id)>{{ $department->name }}</option>@endforeach</select>@error('department_id')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                @if ($creating)
                    <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Temporary password</span><input name="password" type="password" required autocomplete="new-password" class="w-full rounded-lg border-slate-300 text-sm @error('password') border-rose-500 @enderror">@error('password')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                    <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Confirm password</span><input name="password_confirmation" type="password" required autocomplete="new-password" class="w-full rounded-lg border-slate-300 text-sm"></label>
                @endif
            </div>
            <p class="rounded-lg bg-indigo-50 p-3 text-xs leading-5 text-indigo-900">Employee and IT Support accounts must use an active department. Existing ticket records keep their original department.</p>
            <div class="flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-5"><a href="{{ $creating ? route('admin.users.index') : route('admin.users.show', $user) }}" class="ui-button-secondary">Cancel</a><button class="ui-button-primary">{{ $creating ? 'Create account' : 'Save changes' }}</button></div>
        </form>
    </div>
@endsection
