@extends('layouts.app')
@section('title', $creating ? 'Create user' : 'Edit user')
@section('topline', 'User management')
@section('content')
    <a href="{{ $creating ? route('admin.users.index') : route('admin.users.show', $user) }}" class="text-sm font-semibold text-slate-500 hover:text-indigo-700">← Back to users</a>
    <div class="mx-auto mt-5 max-w-3xl"><div class="mb-5"><p class="text-sm font-semibold text-indigo-700">Administrator access</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ $creating ? 'Create user' : 'Edit user' }}</h1><p class="mt-1 text-sm text-slate-500">Role and department are validated together. Passwords are never shown after creation.</p></div>
        <form method="POST" action="{{ $creating ? route('admin.users.store') : route('admin.users.update', $user) }}" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
            @csrf @unless($creating) @method('PATCH') @endunless
            <div class="grid gap-4 sm:grid-cols-2">
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Full name</span><input name="name" required maxlength="255" value="{{ old('name', $user->name) }}" class="w-full rounded-lg border-slate-300 text-sm @error('name') border-rose-500 @enderror">@error('name')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Email</span><input name="email" type="email" required maxlength="255" value="{{ old('email', $user->email) }}" class="w-full rounded-lg border-slate-300 text-sm @error('email') border-rose-500 @enderror">@error('email')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Employee ID</span><input name="employee_id" maxlength="50" value="{{ old('employee_id', $user->employee_id) }}" class="w-full rounded-lg border-slate-300 text-sm @error('employee_id') border-rose-500 @enderror">@error('employee_id')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Phone</span><input name="phone" maxlength="30" value="{{ old('phone', $user->phone) }}" class="w-full rounded-lg border-slate-300 text-sm @error('phone') border-rose-500 @enderror">@error('phone')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Role</span><select name="role" required @disabled(! $creating && auth()->user()->is($user)) class="w-full rounded-lg border-slate-300 text-sm @error('role') border-rose-500 @enderror">@foreach ($roles as $role)<option value="{{ $role->value }}" @selected(old('role', $user->role?->value ?? \App\Enums\UserRole::Employee->value) === $role->value)>{{ $role->label() }}</option>@endforeach</select>@error('role')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Department</span><select name="department_id" class="w-full rounded-lg border-slate-300 text-sm @error('department_id') border-rose-500 @enderror"><option value="">{{ 'No department (admin only)' }}</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected((string) old('department_id', $user->department_id) === (string) $department->id)>{{ $department->name }}</option>@endforeach</select>@error('department_id')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                @if ($creating)
                    <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Temporary password</span><input name="password" type="password" required autocomplete="new-password" class="w-full rounded-lg border-slate-300 text-sm @error('password') border-rose-500 @enderror">@error('password')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
                    <label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Confirm password</span><input name="password_confirmation" type="password" required autocomplete="new-password" class="w-full rounded-lg border-slate-300 text-sm"></label>
                @endif
            </div>
            <p class="rounded-lg bg-indigo-50 p-3 text-xs leading-5 text-indigo-900">Employee and IT Support accounts must use an active department. Existing ticket records keep their original department.</p>
            <div class="flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-5"><a href="{{ $creating ? route('admin.users.index') : route('admin.users.show', $user) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">{{ $creating ? 'Create account' : 'Save changes' }}</button></div>
        </form>
    </div>
@endsection
