@extends('layouts.app')
@section('title', 'Users')
@section('topline', 'User management')
@section('content')
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-700">Directory</p><h1 class="mt-1 text-2xl font-bold text-slate-950">Users</h1><p class="mt-1 text-sm text-slate-500">Manage roles, account status, and departments.</p></div><a href="{{ route('admin.users.create') }}" class="ui-button-primary">Create user</a></div>
    <form method="GET" class="mb-5 grid gap-3 ui-card p-4 shadow-sm sm:grid-cols-2 xl:grid-cols-6">
        <label class="xl:col-span-2"><span class="mb-1 block text-xs font-semibold text-slate-600">Search</span><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Name, email, employee ID" class="w-full rounded-lg border-slate-300 text-sm"></label>
        <label><span class="mb-1 block text-xs font-semibold text-slate-600">Role</span><select name="role" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All roles</option>@foreach ($roles as $role)<option value="{{ $role->value }}" @selected(($filters['role'] ?? '') === $role->value)>{{ $role->label() }}</option>@endforeach</select></label>
        <label><span class="mb-1 block text-xs font-semibold text-slate-600">Department</span><select name="department_id" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All departments</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected((string) ($filters['department_id'] ?? '') === (string) $department->id)>{{ $department->name }}</option>@endforeach</select></label>
        <label><span class="mb-1 block text-xs font-semibold text-slate-600">Account</span><select name="active" class="w-full rounded-lg border-slate-300 text-sm"><option value="">All</option><option value="active" @selected(($filters['active'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['active'] ?? '') === 'inactive')>Inactive</option></select></label>
        <label><span class="mb-1 block text-xs font-semibold text-slate-600">Sort</span><select name="sort" class="w-full rounded-lg border-slate-300 text-sm"><option value="name">Name</option><option value="email" @selected(($filters['sort'] ?? '') === 'email')>Email</option><option value="role" @selected(($filters['sort'] ?? '') === 'role')>Role</option><option value="created_at" @selected(($filters['sort'] ?? '') === 'created_at')>Date added</option></select></label>
        <div class="flex items-end gap-2 sm:col-span-2 xl:col-span-6"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Apply filters</button><a href="{{ route('admin.users.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Clear</a></div>
    </form>
    <section class="ui-card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="ui-table-head"><tr><th class="px-5 py-3">User</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Department</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Added</th><th class="px-5 py-3"><span class="sr-only">Actions</span></th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse ($users as $user)<tr><td class="px-5 py-4"><a href="{{ route('admin.users.show', $user) }}" class="font-semibold text-slate-900 hover:text-indigo-700">{{ $user->name }}</a><span class="mt-0.5 block text-xs text-slate-500">{{ $user->email }}{{ $user->employee_id ? ' · '.$user->employee_id : '' }}</span></td><td class="px-5 py-4 text-slate-700">{{ $user->role->label() }}</td><td class="px-5 py-4 text-slate-700">{{ $user->department?->name ?? '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $user->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $user->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-5 py-4 text-slate-500">{{ $user->created_at->format('M j, Y') }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.users.edit', $user) }}" class="font-semibold text-indigo-700">Edit</a></td></tr>
        @empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-500">No users match these filters.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $users->links() }}</div></section>
@endsection
