@extends('layouts.app')
@section('title', $user->name)
@section('topline', 'User details')
@section('content')
    <a href="{{ route('admin.users.index') }}" class="text-sm font-semibold text-slate-500 hover:text-indigo-700">← Back to users</a>
    <div class="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><span class="grid size-12 place-items-center rounded-full bg-indigo-100 font-bold text-indigo-700">{{ $user->initials }}</span><h1 class="mt-4 text-2xl font-bold text-slate-950">{{ $user->name }}</h1><p class="mt-1 text-sm text-slate-500">{{ $user->email }}</p></div><a href="{{ route('admin.users.edit', $user) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Edit user</a></div>
            <dl class="mt-7 grid gap-5 border-t border-slate-100 pt-6 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Role</dt><dd class="mt-1 text-sm font-semibold text-slate-900">{{ $user->role->label() }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Department</dt><dd class="mt-1 text-sm font-semibold text-slate-900">{{ $user->department?->name ?? 'Not assigned' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Employee ID</dt><dd class="mt-1 text-sm text-slate-900">{{ $user->employee_id ?: '—' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Phone</dt><dd class="mt-1 text-sm text-slate-900">{{ $user->phone ?: '—' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Created</dt><dd class="mt-1 text-sm text-slate-900">{{ $user->created_at->format('M j, Y g:i A') }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Last profile change</dt><dd class="mt-1 text-sm text-slate-900">{{ $user->updated_at->format('M j, Y g:i A') }}</dd></div></dl>
        </section>
        <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Account status</h2><p class="mt-2"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $user->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $user->is_active ? 'Active' : 'Inactive' }}</span></p>
            @can('updateStatus', $user)<form method="POST" action="{{ route('admin.users.status', $user) }}" class="mt-5">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $user->is_active ? '0' : '1' }}"><button class="w-full rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $user->is_active ? 'Deactivate account' : 'Activate account' }}</button></form>@else<p class="mt-4 text-xs leading-5 text-slate-500">Administrators cannot change their own account status.</p>@endcan
        </aside>
    </div>
@endsection
