@extends('layouts.app')
@section('title', 'Edit '.$priority->name.' priority')
@section('topline', 'Configuration')
@section('content')
    <div class="ui-page-toolbar mb-6"><a href="{{ route('admin.priorities.index') }}" class="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-700 transition hover:text-violet-900">← Back to priorities</a><div class="mt-3 flex items-start gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl ring-1 ring-inset ring-indigo-100" style="background-color: {{ $priority->color }}18; color: {{ $priority->color }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5"><path stroke-linecap="round" stroke-linejoin="round" d="m12 3 2.4 5 5.6.8-4 3.9.9 5.5-4.9-2.6-4.9 2.6.9-5.5-4-3.9 5.6-.8L12 3Z"/></svg></span><div><p class="ui-eyebrow">Priority level {{ $priority->level }} · SLA targets</p><h1 class="ui-page-title text-2xl">{{ $priority->name }}</h1><p class="mt-1 text-sm text-slate-500">Names and numeric levels are fixed to preserve the existing priority system.</p></div></div></div>
    <div class="mx-auto max-w-2xl"><form method="POST" action="{{ route('admin.priorities.update', $priority) }}" class="ui-form-card">@csrf @method('PATCH')
        <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Description</span><textarea name="description" rows="4" maxlength="2000" class="w-full rounded-lg border-slate-300 text-sm @error('description') border-rose-500 @enderror">{{ old('description', $priority->description) }}</textarea>@error('description')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <label class="block max-w-xs"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Badge color</span><input type="color" name="color" value="{{ old('color', $priority->color) }}" class="h-11 w-full rounded-lg border-slate-300">@error('color')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Response target (minutes)</span><input type="number" min="1" max="525600" name="sla_response_minutes" required value="{{ old('sla_response_minutes', $priority->sla_response_minutes) }}" class="w-full rounded-lg border-slate-300 text-sm">@error('sla_response_minutes')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label><label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Resolution target (minutes)</span><input type="number" min="1" max="525600" name="sla_resolution_minutes" required value="{{ old('sla_resolution_minutes', $priority->sla_resolution_minutes) }}" class="w-full rounded-lg border-slate-300 text-sm">@error('sla_resolution_minutes')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label></div>
        <label class="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $priority->is_active)) class="rounded border-slate-300 text-indigo-600"><span><span class="block text-sm font-semibold text-slate-800">Active</span><span class="block text-xs text-slate-500">Keep available on new tickets.</span></span></label>
        <div class="flex justify-end gap-2 border-t border-slate-100 pt-5"><a href="{{ route('admin.priorities.index') }}" class="ui-button-secondary">Cancel</a><button class="ui-button-primary">Save priority settings</button></div>
    </form></div>
@endsection
