@extends('layouts.app')
@section('title', 'Edit '.$priority->name.' priority')
@section('topline', 'Configuration')
@section('content')
    <a href="{{ route('admin.priorities.index') }}" class="text-sm font-semibold text-slate-500 hover:text-indigo-700">← Back to priorities</a>
    <div class="mx-auto mt-5 max-w-2xl"><div class="mb-5"><p class="text-sm font-semibold text-indigo-700">Priority level {{ $priority->level }}</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ $priority->name }}</h1><p class="mt-1 text-sm text-slate-500">Names and numeric levels are fixed to preserve the existing priority system.</p></div><form method="POST" action="{{ route('admin.priorities.update', $priority) }}" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">@csrf @method('PATCH')
        <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Description</span><textarea name="description" rows="4" maxlength="2000" class="w-full rounded-lg border-slate-300 text-sm @error('description') border-rose-500 @enderror">{{ old('description', $priority->description) }}</textarea>@error('description')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <label class="block max-w-xs"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Badge color</span><input type="color" name="color" value="{{ old('color', $priority->color) }}" class="h-11 w-full rounded-lg border-slate-300">@error('color')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Response target (minutes)</span><input type="number" min="1" max="525600" name="sla_response_minutes" required value="{{ old('sla_response_minutes', $priority->sla_response_minutes) }}" class="w-full rounded-lg border-slate-300 text-sm">@error('sla_response_minutes')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label><label><span class="mb-1.5 block text-sm font-semibold text-slate-700">Resolution target (minutes)</span><input type="number" min="1" max="525600" name="sla_resolution_minutes" required value="{{ old('sla_resolution_minutes', $priority->sla_resolution_minutes) }}" class="w-full rounded-lg border-slate-300 text-sm">@error('sla_resolution_minutes')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label></div>
        <label class="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $priority->is_active)) class="rounded border-slate-300 text-indigo-600"><span><span class="block text-sm font-semibold text-slate-800">Active</span><span class="block text-xs text-slate-500">Keep available on new tickets.</span></span></label>
        <div class="flex justify-end gap-2 border-t border-slate-100 pt-5"><a href="{{ route('admin.priorities.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">Save priority settings</button></div>
    </form></div>
@endsection
